---
abstract: 'Perl interface to libxine'
author:
  - 'Stephen Nelson <stephenenelson@mac.com>'
build_requires:
  ExtUtils::CBuilder: 0
configure_requires:
  ExtUtils::PkgConfig: 0
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Video-Xine
provides:
  Video::Xine:
    file: lib/Video/Xine.pm
    version: 0.20
  Video::Xine::Driver::Audio:
    file: lib/Video/Xine/Driver/Audio.pm
    version: 0
  Video::Xine::Driver::Video:
    file: lib/Video/Xine/Driver/Video.pm
    version: 0
  Video::Xine::Event:
    file: lib/Video/Xine/Event.pm
    version: 0
  Video::Xine::Event::Queue:
    file: lib/Video/Xine/Event/Queue.pm
    version: 0
  Video::Xine::OSD:
    file: lib/Video/Xine/OSD.pm
    version: 0
  Video::Xine::Stream:
    file: lib/Video/Xine/Stream.pm
    version: 0
  Video::Xine::Util:
    file: lib/Video/Xine/Util.pm
    version: 0
recommends:
  DateTime::Format::Duration: 0
  perl: v5.8.5
requires:
  DateTime: 0
  X11::FullScreen: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.20
x_test_requires:
  Test::More: 0.01
