---
name: Video-Xine
version: 0.16
author:
  - 'Stephen Nelson, E<lt>stephen@cpan.orgE<gt>'
abstract: Perl interface to libxine
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DateTime: 0
  ExtUtils::CBuilder: 0
  Module::Build: 0
  Test::More: 0.01
recommends:
  DateTime::Format::Duration: 0
  X11::FullScreen: 0
  perl: 5.8.5
provides:
  Video::Xine:
    file: lib/Video/Xine.pm
    version: 0.16
  Video::Xine::Driver::Audio:
    file: lib/Video/Xine/Driver/Audio.pm
  Video::Xine::Driver::Video:
    file: lib/Video/Xine/Driver/Video.pm
  Video::Xine::Event:
    file: lib/Video/Xine/Event.pm
  Video::Xine::Event::Queue:
    file: lib/Video/Xine/Event/Queue.pm
  Video::Xine::OSD:
    file: lib/Video/Xine/OSD.pm
  Video::Xine::Stream:
    file: lib/Video/Xine/Stream.pm
  Video::Xine::Utility:
    file: lib/Video/Xine/Utility.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
