---
abstract: 'xine movie player interface'
author:
  - 'Stephen Nelson <stephenenelson@mac.com>'
build_requires:
  FindBin: 0
  Module::Build: 0.3601
  Test::Kwalitee: 0
  Test::More: 0
configure_requires:
  Devel::CheckLib: 1.01
  ExtUtils::PkgConfig: 1.14
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Video-Xine
requires:
  Carp: 0
  DateTime: 0
  Exporter: 0
  Getopt::Long: 0
  Pod::Usage: 0
  X11::FullScreen: 0
  XSLoader: 0
  base: 0
  constant: 0
  perl: v5.8.3
  strict: 0
  warnings: 0
resources:
  repository: https://github.com/stephenenelson/video-xine
version: 0.26
